### ISSUE TITLE
error: cannot access IpregistryClient import co.ipregistry.api.client.IpregistryClient;

### ISSUE THREAD

**Issue by Proxcentaur** [ipregistry/ipregistry-java#1]
Hi, I have been using this library to view my current IP address on android device but I come up with this error:
error: cannot access IpregistryClient
import co.ipregistry.api.client.IpregistryClient;

What should I do?

**Comment by lpellegr** [comment]
@Proxcentaur Thanks for opening this issue.

The current library is not compatible with Android. 

I will publish a working version in the next hours along with a full working example for Android.

**Comment by lpellegr** [comment]
A new version has been released (3.1.1). The library is now compatible with Android.

Here is a fully working Android example that makes use of the new version:
https://github.com/ipregistry/ipregistry-android

 Do not hesitate if you have any questions.

**Comment by Proxcentaur** [comment]
Thank you

**Comment by Proxcentaur** [comment]
How to get the client IP from a request header using this library?

**Comment by lpellegr** [comment]
I suggest looking at the provided example:

https://github.com/ipregistry/ipregistry-android/blob/master/app/src/main/java/com/example/ipregistry_android/IpregistryTask.java#L31

The line `ipregistry.lookup();` performs a remote call to the Ipregistry API. This kind of request is what we call in our docs an [Origin IP lookup](https://ipregistry.co/docs/endpoints#content). It returns the data behind the IP address the API request is coming from. If I understand correctly, this is what you want.

There is no provided method to get the client IP from a request header since this is specific to the infrastructure/network and server you are using. It's up to you to read/parse the header value you need, then you can pass the IP address to the lookup method as such `ipregistry.lookup("1.2.3.4")`. In that case, you will get IP Info for the provided IP address, namely _1.2.3.4_ in this example.

**Comment by Proxcentaur** [comment]
Thanks, I have read it carefully through the documentation too
